### ISSUE TITLE
Root password

### ISSUE THREAD

**Issue by DrOctogon** [AppScale/appscale-tools#164]
When running "appscale up" or "appscale-run-instances" for the first time, the SSH key is copied to the machine. However, if the user has not set a root password before doing so, he/she is unable to complete the process. Users must be instructed to create a root password before deploying AppScale.

**Comment by cdonati** [comment]
I'm not sure at what point this was fixed, but if passwordless SSH is set up between machines in a cluster, the tools can start appscale without a root password being defined.
