### ISSUE TITLE
Homebrew friendly version

### ISSUE THREAD

**Issue by samitheberber** [AppScale/appscale-tools#337]
I created a formula, which successfully installs appscale-tools. However when I ran script, for example `appscale init cluster`, I faced problems that templates couldn't be found etc.

So I'm here to ask if it would be good to place them under `share/appscale` or some other directory and then they would be available from `/usr/local/share/appscale/`.

My current version of formula: https://github.com/samitheberber/homebrew/blob/appscale-tools/Library/Formula/appscale-tools.rb

**Comment by cdonati** [comment]
The homebrew formula has been updated quite a few times since this issue was created. If you encounter any issues using it, feel free to open a new issue.
