### ISSUE TITLE
README.md for OSX

### ISSUE THREAD

**Issue by aidanlane** [AppScale/appscale-tools#424]
Should it say `sudo bash osx/appscale_install.sh` instead of `sudo bash osx/appscale_build.sh`, as the latter doesn't exist?

Also, should 2.2.0 be marked as the latest release? Current "Latest Release" is still 2.0.0, not even 2.1.0.

Thanks!

**Comment by nlake44** [comment]
https://github.com/AppScale/appscale-tools/pull/425

**Comment by aidanlane** [comment]
Thanks! Close now?
