### ISSUE TITLE
Latest release version? 3.5.0 or 3.5.2?

### ISSUE THREAD

**Issue by ilovezfs** [AppScale/appscale-tools#699]
https://github.com/AppScale/appscale-tools/releases shows a 3.5.0, 3.5.1, and 3.5.2
https://github.com/AppScale/appscale-tools/releases/latest points to 3.5.0

Is the current release 3.5.0, 3.5.2 or something else?

**Comment by scragraham** [comment]
Hi @ilovezfs,

appscale-tools is still 3.5.0. We've released two point releases of appscale: 3.5.1 and 3.5.2. We didn't push out a new tools release since nothing changed on the tools side and the tools are point release compatible.

Thanks,
Steve
