### ISSUE TITLE
SSH login problems when starting cloud-mode on GCE

### ISSUE THREAD

**Issue by dmitrii** [AppScale/appscale-tools#715]
I generated AppScalefile with 'appscale init cloud' (on MacOS) and configured to use GCE, pointing client_secrets to a file I got from GCP console. I am using AppScale 3.5.3 image. Running 'appscale up' fails with:

`message : Executing command 'ssh -F /dev/null -i /Users/dmitrii/.appscale/appscale3bd920bcdac84af9b766e3f2401a5ef6.key -o LogLevel=quiet -o NumberOfPasswordPrompts=0 -o StrictHostkeyChecking=no -o UserKnownHostsFile=/dev/null dmitrii@35.224.204.48 bash sudo touch /root/.ssh/authorized_keys' failed`

I see two problems:

1. The user in the above SSH command is wrong. (The tool seems to be picking up my MacOS user.)

2. The key SSH is using is not present anywhere on the instance. (Not in any authorized_keys. And there is no key associated with the instance.)

**Comment by scragraham** [comment]
I'm not able to reproduce this exact issue on OSX or Linux, I suspect that there is a GCE issue where the key is not getting put into your project's metadata. 'appscale up' is getting past this point, which is setting up root access to the instance.

I think we should take a look at the following:

- Verify that the client_secrets.json file is correct (don't paste or copy for obvious reasons)
- Examine the metadata in the console for 'sshKeys' if working correctly your local account username should appear at the top of the value.
- Trying appscale 3.6.0 as 3.5.3 has a monit issue that is causing the system to fail to start.
